### ISSUE TITLE
Vertical collection is a bit janky when used with liquid-fire

### ISSUE THREAD

**Issue by iand675** [html-next/vertical-collection#120]
I've got a table with rows that are rendered via `vertical-collection`. I'd like to use liquid-fire to fade the table in, but when I do so the rows in the `vertical-collection` render after the fade animation happens, so there's a noticable pop in of content post-animation. Ideally there'd be a way to coordinate row rendering with liquid-fire so the rows would be rendered prior to fading in, although I'm not sure what that would actually entail in practice...

**Comment by pzuraq** [comment]
Have you tried using the `initialRenderCount` option? 

The pop comes from us waiting for `didInsertElement` and scheduling a RAF, which will be difficult to coordinate with liquid-fire/velocity's animations. We wait so that we can measure the container to tell how many items we need to render (based on the `estimateHeight'). 

However, we added the `initialRenderCount` option for situations where you want some number of items to render on load. It's a static number, so it doesn't incur any measurement cost (no forced layouts), perfect for situations like this and Fastboot.

**Comment by iand675** [comment]
Yes, this seems to be perfect. Thanks for the pointer!

**Comment by ming-codes** [comment]
Is this just a matter of getting everything on the same scheduler?
