### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by erichonkanen** [html-next/vertical-collection#121]
Hello, do you guys plan to add documentation to this library? The aim of this project is promising but without proper documentation it's hard for people coming into it new...

**Comment by pzuraq** [comment]
Hey @erichonkanen, we are planning on adding more thorough docs when we get to v1. In the meantime, there are a lot of examples on mostly complete api documentation on the [demo site](https://html-next.github.io/vertical-collection/#/examples).

Specifically, what do you think is missing from the docs right now that should be added?

**Comment by erichonkanen** [comment]
I didn't see any docs at all I guess just a link to the demo!

**Comment by erichonkanen** [comment]
the only "docs" I see are demo template code and a settings file on the demo link...

for instance I just tried creating a vertical-collection component and got this error yet I don't see `minHeight` described anywhere?

```Uncaught Error: Must provide a `minHeight` value to vertical-collection https://sqwok.dev:4200/assets/vendor.js 233817 13 Error: Must provide a `minHeight` value to vertical-collection
    at Object.assert (helpers.js:39)
    at DynamicRadar._updateConstants (-private.js:478)
    at _nextUpdate.schedule (-private.js:444)
    at Array.execJob (-private.js:139)
    at Scheduler.flush (-private.js:197)
    at _nextFlush.requestAnimationFrame (-private.js:182)```

**Comment by pzuraq** [comment]
You are using an older version of `vertical-collection`. The current latest is `v1.0.0-beta.6`, which has changed `minHeight` to `estimateHeight` and removed the `minHeight` constraint.

**Comment by erichonkanen** [comment]
do you guys offer consulting if we can't figure this out? it's a critical part of our project im on slack @holler

**Comment by BryanCrotaz** [comment]
I just installed with `ember install` and got beta 4

**Comment by BryanCrotaz** [comment]
Looks like you haven't published beta 6:

from NPM
pzuraq pzuraq published 2 months ago
1.0.0-beta.4 is the latest of 6 releases
github.com/html-next/vertical-collection

**Comment by pzuraq** [comment]
It's published:

```
$ npm show @html-next/vertical-collection versions

[ '1.0.0-beta.1',
  '1.0.0-beta.2',
  '1.0.0-beta.3',
  '1.0.0-beta.4',
  '1.0.0-beta.5',
  '1.0.0-beta.6' ]
```

However the last version is showing up incorrectly. It may be because we started using npm tags properly with the [np](https://github.com/sindresorhus/np) tool for the last couple of betas. These are beta versions, so I would always double check that you have the latest version installed, you can
do so by listing all versions from NPM or checking the tags, which we always publish for each version.

We should be launching v1.0.0 soon, the only blockers and docs and debug tooling and a final review from @runspired so hopefully this won't be an issue much longer. Going to close this in the meantime.

**Comment by BryanCrotaz** [comment]
I would humbly suggest that the tags are incorrect. Both the npm project page [https://www.npmjs.com/package/@html-next/vertical-collection] and `npm install` give beta-4 as the latest version

**Comment by pzuraq** [comment]
Yes, as I mentioned in my last comment, our publishing process changed for the past 2 beta versions and we are now using the npm `next` tag, so it's probably messed up. The only recourse here would be to unpublish the previous betas, or to push v1.0.0. Since we are very close to 1.0.0 final I think waiting would be the best course of action in case anyone is still using an older beta version.

**Comment by BryanCrotaz** [comment]
Looks as though the `latest` tag may not have been atttached. This could be fixed by publishing a beta-7 with that tag as well as the `next` tag

**Comment by pzuraq** [comment]
👍 sounds good, we did have a bugfix go in so I think publishing beta.7 would be good. I'll push it as soon as I get into the office.

**Comment by pzuraq** [comment]
`beta.7` has been published, and the tags have been fixed

**Comment by BryanCrotaz** [comment]
:) ta muchly

**Comment by runspired** [comment]
There is also always the choice to republish a missing package ;)
