### ISSUE TITLE
scrolling fixed list renders incorrectly

### ISSUE THREAD

**Issue by BryanCrotaz** [html-next/vertical-collection#124]
I have a list of 50 objects, rendered in `vertical-collection` `beta-7`. As you can see from the timeline image scrolling is broken:

![vertical-collection](https://user-images.githubusercontent.com/2016523/29411919-a4e5430e-834e-11e7-9b53-3adbe6528330.png)

It starts by filling the height + a couple at the bottom. As you scroll it doesn't add new items until we reach the estimatedHeight at the top

**Comment by pzuraq** [comment]
Can you post the your usage of VC, along with the CSS you're using it with?

**Comment by pzuraq** [comment]
Based on the symptoms and similar issues I've had recently I'm going to say that this is being caused by incorrect CSS container styles. Something like this could cause the issue:

```
<div class="scroll-container">
  <div style="height: 100%;">
    {{#vertical-collection items as |item|}}

    {{/vertical-collection}}
  </div>
</div>
```

Note that the immediate parent of the VC is not the scroll container, and the VC does not have `containerSelector` set to tell it to not use the immediate parent but the actual scroll container. The intermediate div, which VC _thinks_ is the scroll container, has height 100% so set so it fills up the true scroll container and VC renders correctly initially, but it cannot pick up scroll events as they do not occur on the correct element so it appears to stop working.

There are other possible issues but without more details I can't diagnose. Going to close for now, feel free to reopen with a more detailed description.

**Comment by BryanCrotaz** [comment]
Could you add some documentation around this? It's certainly not obvious from the documentation that's there, but it makes sense now you say it.

**Comment by pzuraq** [comment]
Yes, we're working on docs for the v1 release, will add a section on scroll containers
