### ISSUE TITLE
Ember upgrade issue (browser passive event handler causes exit loop scheduler problem)

### ISSUE THREAD

**Issue by josh803316** [html-next/vertical-collection#197]
cc: @pzuraq 

(Related Issue)
https://github.com/html-next/ember-raf-scheduler/issues/5

(Ember-Slack Discussion)
https://embercommunity.slack.com/archives/C0ASUJT3M/p1521828395000226

Context:
It seems that when the browser does not support passive event handlers there is an issue with the scheduler and exiting the scheduling loop. 

In my specific case the test that started failing after upgrade was this:
https://github.com/ming-codes/ember-ui-kit/blob/master/tests/integration/components/ui-table--v2-test.js#L151

I noticed that only 4 rows were being rendered instead of 12.... @pzuraq is aware of this issue via discussions in Ember slack

**Comment by andrewfan** [comment]
@josh803316 Hey, Josh, did you find a workaround?

**Comment by andrewfan** [comment]
@josh803316 my error happened because inside my component I manually called radar.start() (which added new scroll handler) and did not call radar.destroy()
so once the next test stated there was an existing handler for the element and the polling started 
https://github.com/html-next/vertical-collection/blob/master/addon/-private/data-view/utils/scroll-handler.js#L53

**Comment by josh803316** [comment]
@andrewfan I moved off Ember projects when I changed companies so I never resolved this and not sure if it was resolved by others. Sorry I can't be more help.

**Comment by rwwagner90** [comment]
Since this is old, and @josh803316 is not sure of the details, I am closing for now. Please open another issue if you are still having problems!
