### ISSUE TITLE
Transpiling error in Ember 4 without embroider

### ISSUE THREAD

**Issue by BryanCrotaz** [html-next/vertical-collection#393]
The below only happens when not using embroider.

Line 352 of radar.js
```
    assert('Must provide a `estimateHeight` value to vertical-collection', estimateHeight !== null);
```
is being transpiled to
```
      (!(estimateHeight !== null) && Ember.assert('Must provide a `estimateHeight` value to vertical-collection', estimateHeight !== null));
```
This causes the error `Ember is not defined` 

[package.json](https://github.com/html-next/vertical-collection/files/9952854/package.json.txt)

**Comment by BryanCrotaz** [comment]
Can reproduce with a new app:
```bash
ember new test-transpile
cd test-transpile
ember install @html-next/vertical-collection
ember g controller application
ember s
```
In application controller:
```js
get items() {
  return ['a', 'b'];
}
```
In application template:
```html
<VerticalCollection @items={{this.items}} as |item|>
  <div>{{item}}</div>
</VerticalCollection>
```

**Comment by ef4** [comment]
I found the problem. vertical-collection's customized rollup-based build is not compatible with ember 4, because it uses `compileModules: false` here:

https://github.com/html-next/vertical-collection/blob/f8ba1139b0d5ce2573c66d8b702e99eaadef3c76/index.js#L73

But in ember-cli-babel, that forces you into globals mode, meaning `import { assert } from '@ember/debug'` gets compiled to `Ember.assert()`, which doesn't exist anymore starting at Ember 4. See:

https://github.com/babel/ember-cli-babel/blob/3ce768ada9202c0455f87511ab95acf667d0c97e/lib/babel-options-util.js#L94-L98

The comment there suggests you can set `disableDebugTooling` to true to stop this behavior.

But really vertical-collection should absolutely just delete all this custom build code.

The reason it works on Embroider is that Embroider already ships with a compatibility rule that completely ignores vertical-collection's custom build, because that build is fragile and locked into the classic ember-cli 3.x way of doing things:

https://github.com/embroider-build/embroider/blob/d31bee3c8fafdea6308b80642b5e56971cfd0caa/packages/compat/src/compat-adapters/%40html-next/vertical-collection.ts
