### ISSUE TITLE
[META] can we loosen min-height requirements?

### ISSUE THREAD

**Issue by runspired** [html-next/vertical-collection#71]
See (among others): https://github.com/runspired/smoke-and-mirrors/issues/127

**Comment by pzuraq** [comment]
The current issue with this would be our strategy for the VirtualComponentPool. If we want to allow arbitrary heights below the minHeight, we may end up not rendering enough items at all.

If we can performantly check the heights and update the pool as needed, then the restriction could be changed to minHeight > 0

**Comment by pzuraq** [comment]
From offline discussion, we can also warn instead of error when an item below minimum height is encountered. Technically, items can go below the minHeight and everything should Just Work, and it should be the user's responsibility to make sure that they don't go below that height often enough to stop showing at all.

**Comment by pzuraq** [comment]
Loosened with the `minHeight` -> `estimateHeight` refactor. Closing this.
