### ISSUE TITLE
`private` fails to compile correctly on Ember-CLI 2.11

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#96]
```
_verticalCollectionPrivate.Token is not a constructor error TypeError: _verticalCollectionPrivate.Token is not a constructor
```

**Comment by v3ss0n** [comment]
happening to me

**Comment by pzuraq** [comment]
@v3ss0n this is an issue with ember-cli specifically since what's happening is it's not including a module in the final build. Can you post some information about your ember-cli setup?

**Comment by v3ss0n** [comment]
i had updated to ember cli 2.13.2 and all is fine now.
my setup was node 6.4 , ember-cli 2.10

**Comment by alash2k** [comment]
Is there anything we can do to make it work with ember-cli 2.10 ?

**Comment by pzuraq** [comment]
@alash2k there probably is, but at this point we're focussing on solidifying the component and prepping for v1.0.0, so it will probably have to wait until after that. PRs are always welcome, and you can also upgrade Ember-CLI without upgrading Ember itself (we're currently using Ember 1.11 with Ember-CLI 2.8)

**Comment by alash2k** [comment]
Thanks Chris. I did try to update ember CLI to 2.13.2 with ember 2.10. I am
also on ember engines which I can't upgrade as well. Will see if I can come
up with a fix that I can do a PR. Just for the sake of testing, I imported
private with something like 'import private from ../private/index' and it
worked.. not sure if that's good enough...


Radha

On Jun 20, 2017 8:42 PM, "Chris Garrett" <notifications@github.com> wrote:

@alash2k <https://github.com/alash2k> there probably is, but at this point
we're focussing on solidifying the component and prepping for v1.0.0, so it
will probably have to wait until after that. PRs are always welcome, and
you can also upgrade Ember-CLI without upgrading Ember itself (we're
currently using Ember 1.11 with Ember-CLI 2.8)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/html-next/vertical-collection/issues/96#issuecomment-309938499>,
or mute the thread

**Comment by pzuraq** [comment]
I haven't been able to reproduce this, if it's still an issue with the latest beta feel free to reopen this issue with reproduction steps. Closing for now.
